### ISSUE TITLE
Add ability to execute ANY command defined by other packages

### ISSUE THREAD

**Issue by kyleries** [VoiceCode/atom-voicecode#5]
Currently, it seems, only 'workspace' commands are working.

Ref: https://voicecode.slack.com/archives/general/p1450132548000549

I'm just getting my feet wet with atom and voice code, but this is definitely something that I can at least start looking into, perhaps including a bit of research findings in this issue.

**Comment by unboundmusic** [comment]
@kyleries that would be very cool. Let me know if you have any questions I can help with. A tangential project to this is figuring out a way to send arbitrary javascript from VoiceCode to Atom and have it `eval`ed - this would give a lot of flexibility but it is currently blocked from executing because of security constraints in Atom/Electron/Chrome - same as trying to inject js in a webpage.

**Comment by dimatter** [comment]
https://github.com/atom/loophole

reminded me of:
https://www.youtube.com/watch?v=j8ZF_R_j0OY

**Comment by dimatter** [comment]
can be closed

**Comment by unboundmusic** [comment]
This is fixed in the branch called 'remote' which works with the 'electron' VoiceCode branch
